### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by mycode-bit** [Alex-CompEcon/5UTR#1]
Hello,
I did not see the place to download the data:  All_Variants.tar.gz. 
There is no data_dict.pkl and Modelling.ipynb either. 
Where could I find those files?

Thanks
Bill

**Comment by Karollus** [comment]
Sorry about that, I forgot to replace the placeholder in the readme. I hope it is clearer now. If not, do not hesitate to ask.

Best,
Alex

**Comment by mycode-bit** [comment]
thanks
